# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 8 * * *"

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Prepare Git
      run: |
        git config --global user.name "mcc-devel"
        git config --global user.email "jettzheng@foxmail.com"
        git config --global user.author "mcc-devel"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --pre pip
        pip install --pre wheel
        pip install --pre requests pyecharts
    - name: Run program
      run: |
        python corona-advanced.py
    - name: Push files
      run: |
        git add Corona-confirms.html Corona-deaths.html Corona-recoveries.html
        git commit -m "Update htmls" Corona-confirms.html Corona-deaths.html Corona-recoveries.html
        git add confirm.csv death.csv recover.csv
        git commit -m "Update csvs" confirm.csv death.csv recover.csv
        git add confirm.json death.json recover.json
        git commit -m "Update jsons" confirm.json death.json recover.json
        git push
